name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to destroy (dev, staging, prod)"
        required: true
        default: dev
        type: choice
        options:
          - dev
          - staging
          - prod

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
  WORKING_DIR: oblig2/deployments

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Terraform Init
        run: terraform init
        working-directory: ${{ env.WORKING_DIR }}

      - name: Select or Create Workspace
        run: |
          terraform workspace select ${{ github.event.inputs.environment }} || terraform workspace new ${{ github.event.inputs.environment }}
        working-directory: ${{ env.WORKING_DIR }}

      - name: Terraform Destroy
        run: |
          terraform destroy --auto-approve -var-file="${{ env.WORKING_DIR }}/terraform.tfvars.${{ github.event.inputs.environment }}" -var="admin_password=${{ env.ADMIN_PASSWORD }}"
        working-directory: ${{ env.WORKING_DIR }}
