name: Destroy Infrastructure

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Specify the environment to destroy (test or prod)"
        required: true
        default: "test"
        type: choice
        options:
          - test
          - prod

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
  WORKING_DIR: ./oblig2

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Terraform Init
        run: terraform init
        working-directory: ${{ env.WORKING_DIR }}

      - name: Select Workspace
        run: |
          if [ "${{ github.event.inputs.environment }}" == "prod" ]; then
            terraform workspace select prod || terraform workspace new prod
          elif [ "${{ github.event.inputs.environment }}" == "test" ]; then
            terraform workspace select staging || terraform workspace new staging
          fi
        working-directory: ${{ env.WORKING_DIR }}

      - name: Terraform Destroy
        run: terraform destroy --auto-approve -var-file="terraform.tfvars.${{ github.event.inputs.environment }}"
        working-directory: ${{ env.WORKING_DIR }}
