name: Terraform Prod Test

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy"
        required: true
        default: prod
        type: choice
        options:
          - prod

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
  WORKING_DIR: oblig2/deployments

jobs:
  prod:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Terraform Init
        run: terraform init
        working-directory: ${{ env.WORKING_DIR }}

      - name: Terraform workspace select or create prod
        run: terraform workspace select prod || terraform workspace new prod
        working-directory: ${{ env.WORKING_DIR }}

      - name: Terraform Plan Prod
        run: terraform plan -var-file="terraform.tfvars.prod" -var="admin_password=${{ env.ADMIN_PASSWORD }}"
        working-directory: ${{ env.WORKING_DIR }}

      - name: Terraform Apply Prod
        run: terraform apply --auto-approve -var-file="terraform.tfvars.prod" -var="admin_password=${{ env.ADMIN_PASSWORD }}"
        working-directory: ${{ env.WORKING_DIR }}
